name: astral-uv
base: core24
version: 0.4.12
summary: An extremely fast Python package installer and resolver, written in Rust.
description: |
  An extremely fast Python package installer and resolver, written in Rust. Designed as a drop-in replacement for common pip and pip-tools workflows.

grade: stable
confinement: classic

platforms:
  amd64:
  arm64:
  ppc64el:
  riscv64:
  s390x:

parts:
  uv:
    plugin: rust
    source: https://github.com/astral-sh/uv.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - cmake
    build-attributes:
      - enable-patchelf
    organize:
      uv: bin/uv
      uvx: bin/uvx
      lib*.so: lib/
  completion:
    plugin: nil
    after: [uv]
    override-build: |
      "${CRAFT_STAGE}/bin/uv" generate-shell-completion bash > "${CRAFT_PART_INSTALL}/uv-completion.bash"
      echo 'complete -F _uv -o bashdefault -o default astral-uv.uv' >> "${CRAFT_PART_INSTALL}/uv-completion.bash"
      echo 'complete -F _uv -o bashdefault -o default uv' >> "${CRAFT_PART_INSTALL}/uv-completion.bash"
apps:
  uv:
    command: bin/uv
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
    completer: uv-completion.bash
  uvx:
    command: bin/uvx
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
