name: astral-uv
title: uv (by Astral)
base: core24
version: 0.11.28
summary: An extremely fast Python package installer and resolver, written in Rust.
description: |
  An extremely fast Python package installer and resolver, written in Rust. Designed as a drop-in replacement for common pip and pip-tools workflows.

grade: stable
confinement: classic

package-repositories:
  - type: apt
    architectures: [$CRAFT_ARCH_BUILD_FOR]
    formats: [deb, deb-src]
    components: [main]
    suites: [noble, noble-updates, noble-backports]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    url: http://ports.ubuntu.com/ubuntu-ports

platforms:
  armhf:
    build-on: [arm64, amd64]
    build-for: [armhf]

parts:
  uv:
    plugin: rust
    source: https://github.com/astral-sh/uv.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    # build-attributes:  # Disabled due to https://github.com/canonical/snapcraft/issues/5836
    #   - enable-patchelf
    build-environment:
      # Build a static binary. Needed for armhf because of https://github.com/canonical/snapcraft/issues/5836
      - CARGO_BUILD_TARGET: armv7-unknown-linux-musleabihf
      - CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_LINKER: rust-lld
      - CARGO_CFG_TARGET_FEATURE: crt-static
      - CC: clang-20
      - CARGO_PROFILE_RELEASE_LTO: "off"
      # See: https://github.com/lengau/uv-snap/issues/10
      - to arm64:
        - JEMALLOC_SYS_WITH_LG_PAGE: "16"
      - to ppc64el:
        - JEMALLOC_SYS_WITH_LG_PAGE: "16"
    build-packages:
      - libclang-20-dev
      - cmake
      - gcc-arm-linux-gnueabihf
      - libc6-dev-$CRAFT_ARCH_BUILD_FOR-cross
      # Use clang for the armhf build so we can build for musl.
      - clang-20
      - musl-dev
      - musl-tools
    # rust-features:
    #   - crt-static
    organize:
      uv: bin/uv
      uvx: bin/uvx
      lib*.so: lib/
    override-build: |
      rustup target add ${CARGO_BUILD_TARGET}
      craftctl default
      # manually install binaries as their target dir differs
      find ./target/${CARGO_BUILD_TARGET}/release -maxdepth 1 -executable -exec install -Dvm755 '{}' "${CRAFT_PART_INSTALL}/" ';'
  completion:
    plugin: nil
    after: [uv]
    override-build: |
      "${CRAFT_STAGE}/bin/uv" generate-shell-completion bash > "${CRAFT_PART_INSTALL}/uv-completion.bash"
      echo 'complete -F _uv -o bashdefault -o default astral-uv.uv' >> "${CRAFT_PART_INSTALL}/uv-completion.bash"
      echo 'complete -F _uv -o bashdefault -o default uv' >> "${CRAFT_PART_INSTALL}/uv-completion.bash"
  license:
    plugin: dump
    source: .
    source-subdir: licenses
    organize:
      "*": usr/share/doc/uv/
apps:
  uv:
    command: bin/uv
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
    completer: uv-completion.bash
  uvx:
    command: bin/uvx
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
