name: astral-uv
title: uv (by Astral)
base: core24
version: 0.8.15
summary: An extremely fast Python package installer and resolver, written in Rust.
description: |
  An extremely fast Python package installer and resolver, written in Rust. Designed as a drop-in replacement for common pip and pip-tools workflows.

grade: stable
confinement: classic

platforms:
  amd64:
  arm64:
  armhf:
  ppc64el:
  riscv64:
  s390x:

parts:
  uv:
    plugin: rust
    source: https://github.com/astral-sh/uv.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    build-attributes:
      - enable-patchelf
    build-environment:
      # See: https://github.com/lengau/uv-snap/issues/10
      - to arm64:
        - JEMALLOC_SYS_WITH_LG_PAGE: 16
      - to ppc64el:
        - JEMALLOC_SYS_WITH_LG_PAGE: 16
    organize:
      uv: bin/uv
      uvx: bin/uvx
      lib*.so: lib/
    override-build: |
      if [[ "${CRAFT_ARCH_BUILD_FOR}" == "armhf" ]]; then
        # Requires too much RAM to build on armhf, so we cheat and use the upstream binary.
        # This is preferable to cross-compiling because Launchpad won't cross-compile and
        # I really don't want to try to keep up with cross-compiling and releasing for
        # armhf every time there's a release. If someone comes up with a better answer
        # I'd love to replace this with a real build.
        curl -sL https://github.com/astral-sh/uv/releases/download/$SNAPCRAFT_PROJECT_VERSION/uv-armv7-unknown-linux-gnueabihf.tar.gz | tar xz -C "${CRAFT_PART_INSTALL}" --strip-components=1
      else
        craftctl default
      fi
  completion:
    plugin: nil
    after: [uv]
    override-build: |
      "${CRAFT_STAGE}/bin/uv" generate-shell-completion bash > "${CRAFT_PART_INSTALL}/uv-completion.bash"
      echo 'complete -F _uv -o bashdefault -o default astral-uv.uv' >> "${CRAFT_PART_INSTALL}/uv-completion.bash"
      echo 'complete -F _uv -o bashdefault -o default uv' >> "${CRAFT_PART_INSTALL}/uv-completion.bash"
apps:
  uv:
    command: bin/uv
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
    completer: uv-completion.bash
  uvx:
    command: bin/uvx
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
