name: astral-uv
title: uv (by Astral)
base: core24
version: 0.6.3
summary: An extremely fast Python package installer and resolver, written in Rust.
description: |
  An extremely fast Python package installer and resolver, written in Rust. Designed as a drop-in replacement for common pip and pip-tools workflows.

grade: stable
confinement: classic

package-repositories:
  - type: apt
    architectures: [$CRAFT_ARCH_BUILD_FOR]
    formats: [deb, deb-src]
    components: [main]
    suites: [noble, noble-updates, noble-backports]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    url: http://ports.ubuntu.com/ubuntu-ports

platforms:
  armhf:
    build-on: [arm64]
    build-for: [armhf]

parts:
  uv:
    plugin: rust
    source: https://github.com/astral-sh/uv.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - cmake
      - gcc-arm-linux-gnueabihf
      - libc6-dev-$CRAFT_ARCH_BUILD_FOR-cross
    build-environment:
      - CARGO_BUILD_TARGET: "armv7-unknown-linux-gnueabihf"
      - CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc
    build-attributes:
      - enable-patchelf
    organize:
      uv: bin/uv
      uvx: bin/uvx
      lib*.so: lib/
    override-build: |
      rustup target add armv7-unknown-linux-gnueabihf
      craftctl default
      # manually install binaries as their target dir differs
      find ./target/armv7-unknown-linux-gnueabihf/release -maxdepth 1 -executable -exec install -Dvm755 '{}' "${CRAFT_PART_INSTALL}/" ';'

    # override-build: |
    #   if [[ "${CRAFT_ARCH_BUILD_FOR}" == "armhf" ]]; then
    #     # Requires too much RAM to build on armhf, so we cheat and use the upstream binary.
    #     # This is preferable to cross-compiling because Launchpad won't cross-compile and
    #     # I really don't want to try to keep up with cross-compiling and releasing for
    #     # armhf every time there's a release. If someone comes up with a better answer
    #     # I'd love to replace this with a real build.
    #     curl -sL https://github.com/astral-sh/uv/releases/download/$SNAPCRAFT_PROJECT_VERSION/uv-armv7-unknown-linux-gnueabihf.tar.gz | tar xz -C "${CRAFT_PART_INSTALL}" --strip-components=1
    #   else
    #     craftctl default
    #   fi
  completion:
    plugin: nil
    after: [uv]
    override-build: |
      arm-linux-gnueabihf-readelf -a "${CRAFT_STAGE}/bin/uv" | grep "Shared library:"

      echo "###### The End"
      LD_LIBRARY_PATH=/usr/arm-linux-gnueabihf/lib/ "${CRAFT_STAGE}/bin/uv" generate-shell-completion bash > "${CRAFT_PART_INSTALL}/uv-completion.bash"
      echo 'complete -F _uv -o bashdefault -o default astral-uv.uv' >> "${CRAFT_PART_INSTALL}/uv-completion.bash"
      echo 'complete -F _uv -o bashdefault -o default uv' >> "${CRAFT_PART_INSTALL}/uv-completion.bash"
apps:
  uv:
    command: bin/uv
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
    completer: uv-completion.bash
  uvx:
    command: bin/uvx
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
