name: astral-uv
base: core24
version: 0.3.1
summary: An extremely fast Python package installer and resolver, written in Rust.
description: |
  An extremely fast Python package installer and resolver, written in Rust. Designed as a drop-in replacement for common pip and pip-tools workflows.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic

platforms:
  amd64:
  arm64:
  ppc64el:
  riscv64:
  s390x:

parts:
  uv:
    plugin: rust
    source: https://github.com/astral-sh/uv.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - cmake
    build-attributes:
      - enable-patchelf
    organize:
      uv: bin/uv
      uv-dev: bin/uv-dev
      lib*.so: lib/

apps:
  uv:
    command: bin/uv
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
