name: astral-uv
base: core24
version: "0.1.33"
summary: An extremely fast Python package installer and resolver, written in Rust.
description: |
  An extremely fast Python package installer and resolver, written in Rust. Designed as a drop-in replacement for common pip and pip-tools workflows.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic

parts:
  uv:
    plugin: rust
    source: https://github.com/astral-sh/uv.git
    source-tag: 0.1.33
    build-packages:
      - cmake
    build-attributes:
      - enable-patchelf
    stage-packages:
      - git
    organize:
      uv: bin/uv
      uv-dev: bin/uv-dev
      lib*.so: lib/

apps:
  uv:
    command: bin/uv
    plugs:
      - home
      - removable-media
      - network
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
